# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheaterDiscounts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheaterDiscounts

  target 'TheaterDiscountsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'TheaterDiscountsUITests' do
    # Pods for testing
  end

end
